language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t katharinad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true katharinad/react-test npm test

after_success:
  - docker build -t katharinad/multi-client ./client
  - docker build -t katharinad/multi-nginx ./nginx
  - docker build -t katharinad/multi-server ./server
  - docker build -t katharinad/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push katha/multi-client 
  - docker push katha/multi-nginx
  - docker push katha/multi-server
  - docker push katha/multi-worker
