language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t katharinad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true katharinad/react-test npm test

after_success:
  - docker build -t katharinad/multi-client ./client
  - docker build -t katharinad/multi-nginx ./nginx
  - docker build -t katharinad/multi-server ./server
  - docker build -t katharinad/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push katharinad/multi-client 
  - docker push katharinad/multi-nginx
  - docker push katharinad/multi-server
  - docker push katharinad/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-eu-central-1-106205595426"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
